language: python
python:
  - "2.7"
  - "3.6"
addons:
  apt:
    packages:
      - debhelper
      - fakeroot
      - rpm
      - libssl-dev
cache:
  - pip
  - directories:
    - /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/
    - /home/travis/virtualenv/python2.7.13/bin/
install:
  - pip install --upgrade capstone==3.0.5rc2 pwn
script:
  - export PWN_SCHOOL_VERSION=$(rpm -q --qf '%{v}' --specfile pwn-school.spec)
  - mkdir -p ~/rpmbuild/SOURCES && git archive HEAD --prefix=pwn-school-${PWN_SCHOOL_VERSION}/ | gzip > ~/rpmbuild/SOURCES/pwn-school-${PWN_SCHOOL_VERSION}.tar.gz
  - rpmbuild -ba --nodeps pwn-school.spec
  - debian/rules clean
  - debian/rules build
  - fakeroot debian/rules binary
virtualenv:
  system_site_packages: true
