language: python
python:
  - "2.7"
  - "3.6"
addons:
  apt:
    packages:
      - debhelper
      - fakeroot
      - rpm
      - libssl-dev
cache:
  - pip
  - directories:
    - virtualenv
install:
  - pip install --upgrade capstone==3.0.5rc2 pwn
  - git clone --branch=full-3-compat https://github.com/Arusekk/pwntools.git
  - (cd pwntools; pip install --upgrade --editable .)
script:
  - export PWN_SCHOOL_VERSION=$(rpm -q --qf '%{v}' --specfile pwn-school.spec)
  - mkdir -p ~/rpmbuild/SOURCES && git archive HEAD --prefix=pwn-school-${PWN_SCHOOL_VERSION}/ | gzip > ~/rpmbuild/SOURCES/pwn-school-${PWN_SCHOOL_VERSION}.tar.gz
  - rpmbuild -ba --nodeps pwn-school.spec
  - debian/rules clean
  - debian/rules build
  - fakeroot debian/rules binary
