language: python
python:
  - "2.7"
  - "3.6"
addons:
  apt:
    packages:
      - debhelper
      - fakeroot
      - rpm
      - libssl-dev
cache:
  - pip
  - directories:
    - usr
    - /home/travis/virtualenv/python2.7_with_system_site_packages
    - /home/travis/virtualenv/python3.6_with_system_site_packages
install:
  - test -x /home/travis/virtualenv/python3.6_with_system_site_packages/bin/activate || python3 -m virtualenv --system-site-packages /home/travis/virtualenv/python3.6_with_system_site_packages && source /home/travis/virtualenv/python3.6_with_system_site_packages/bin/activate || test -x /home/travis/virtualenv/python2.7_with_system_site_packages/bin/activate || python2 -m virtualenv --system-site-packages /home/travis/virtualenv/python2.7_with_system_site_packages && source /home/travis/virtualenv/python2.7_with_system_site_packages/bin/activate || true
  - pip install --upgrade capstone==3.0.5rc2 pwn
script:
  - export PWN_SCHOOL_VERSION=$(rpm -q --qf '%{v}' --specfile pwn-school.spec)
  - mkdir -p ~/rpmbuild/SOURCES && git archive HEAD --prefix=pwn-school-${PWN_SCHOOL_VERSION}/ | gzip > ~/rpmbuild/SOURCES/pwn-school-${PWN_SCHOOL_VERSION}.tar.gz
  - rpmbuild -ba --nodeps pwn-school.spec
  - debian/rules clean
  - debian/rules build
  - fakeroot debian/rules binary
#virtualenv:
  #system_site_packages: true
