language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - debhelper
      - fakeroot
      - rpm
      - libssl-dev
install:
  - pip install capstone==3.0.5rc2 pwn
script:
  - export PWN_SCHOOL_VERSION=$(rpm -q --qf '%{version}' --specfile pwn-school.spec)
  - mkdir -p ~/rpmbuild/SOURCES && git archive HEAD --prefix=pwn-school-${PWN_SCHOOL_VERSION}/ | gzip > ~/rpmbuild/SOURCES/pwn-school-${PWN_SCHOOL_VERSION}.tar.gz
  - rpmbuild -ba --nodeps pwn-school.spec
  - cd .. && mv pwn-school pwn-school-${PWN_SCHOOL_VERSION}; cd pwn-school*/
  - debian/rules clean
  - debian/rules build
  - fakeroot debian/rules binary
virtualenv:
  system_site_packages: true
